### ISSUE TITLE
how to install this ? 

### ISSUE THREAD

**Issue by mshonak** [maatt/gurushots-auto-vote-and-boost#1]
I try to do  "git clone https://github.com/maatt/gurushots-auto-vote-and-boost.git " and got error 
'git' is not recognized as an internal or external command,
operable program or batch file.

I try also to download the zip file extract it to C:\GurushotsVoter 
I try to install  "npm install -g nodemon"  and  also  "npm install --save-dev nodemon"
I install node from here :   https://nodejs.org/en/
I did "npm install" and "npm start" 
but still got error : 

Error: Cannot find module 'node-cron'
Require stack:
- C:\GurushotsVoter\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\GurushotsVoter\main.js:5:14)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\GurushotsVoter\\main.js' ]
}

I also try to install :  "npm install --save node-cron " and got error  ....... errno -4048...

**Comment by mshonak** [comment]
I disable the node-cron and it working with 
node main.js 

_______________________________________________________________________________________________________________________________
```
const puppeteer = require('puppeteer');
const fs = require('fs');
const config = require('./config.json');
const cookies = require('./cookies.json');

//const cron = require('node-cron');

//const runner = cron.schedule('*/30 * * * *', () => {
   console.clear();
   console.log("   _____                      _           _                       _         __      __   _            \n" +
       "  / ____|                    | |         | |           /\\        | |        \\ \\    / /  | |           \n" +
       " | |  __ _   _ _ __ _   _ ___| |__   ___ | |_ ___     /  \\  _   _| |_ ___    \\ \\  / /__ | |_ ___ _ __ \n" +
       " | | |_ | | | | '__| | | / __| '_ \\ / _ \\| __/ __|   / /\\ \\| | | | __/ _ \\    \\ \\/ / _ \\| __/ _ \\ '__|\n" +
       " | |__| | |_| | |  | |_| \\__ \\ | | | (_) | |_\\__ \\  / ____ \\ |_| | || (_) |    \\  / (_) | ||  __/ |   \n" +
       "  \\_____|\\__,_|_|   \\__,_|___/_| |_|\\___/ \\__|___/ /_/    \\_\\__,_|\\__\\___/      \\/ \\___/ \\__\\___|_|   \n" +
       "                                                                                                      \n" +
       "                                                                                                      ");
   (async () => {
      console.log('Starting Gurushots Auto Voter\n');
      console.log("------------------------------------------------");
      let browser = await puppeteer.launch();
      let page = await browser.newPage();
      await page.setViewport({width: 1200, height: 720})
      await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0');
      await page.goto('https://gurushots.com/', {waitUntil: 'networkidle0', timeout: 0});


      if (!Object.keys(cookies).length) {
         const login = '.modal-login__form > div:nth-child(1) > input';
         const password = '.modal-login__form > div:nth-child(2) > input';
         const loginSubmit = '#dialogContent_0 > md-dialog-content > form > button'

         await page.evaluate(async () => {
            const loginBtn = document.querySelectorAll('header gs-header div > div > protection:nth-child(1) a');
            for (var btn of loginBtn) {
               const style = getComputedStyle(btn);

               if (style.display !== 'none') {
                  await btn.click();
                  break;
               }
            }

         })
         console.log("logging in as " + config.username);
         console.log("------------------------------------------------");
         await page.type(login, config.username);
         await page.type(password, config.password);
         await page.click(loginSubmit);
         await page.waitForNavigation();
         await page.goto("https://gurushots.com/", {waitUntil: "networkidle2", timeout: 0});
         try {
            await page.waitForSelector('[ng-click="$ctrl.goProfile()"]');
         } catch (err) {
            console.log("failed to login");
            process.exit(0);
         }
         let currentCookies = await page.cookies();
         fs.writeFileSync('./cookies.json', JSON.stringify(currentCookies));
      } else {
         console.log(config.username + " is already logged in, redirecting...");
         console.log("------------------------------------------------");
         await page.setCookie(...cookies);
         await page.goto("https://gurushots.com/", {waitUntil: "networkidle2", timeout: 0});
      }

      page.on('console', async e => {
         const args = await Promise.all(e.args().map(a => a.jsonValue()));
         console.log(...args);
      });

      await page.evaluate(async () => {
         console.log("\nBeginning the Vote Session:\n");
         const LetsGo = document.getElementsByClassName('modal-vote__greeting');
         const voteBtns = document.getElementsByClassName('icon-vote-negative');
         const boostBtns = document.getElementsByClassName('boost-state-available');

         console.log("Challenges Available to Vote on:  " + voteBtns.length + "\n");

         for (var btn of voteBtns) {

            $(btn).click();
            await new Promise(resolve => setTimeout(resolve, 4000));
            let title = $('.modal-vote__challenge-title span')[0].innerText;
            console.log("Currently Voting on: " + title);
            $(LetsGo).click();
            const picForVote = $(".modal-vote__photo__voted").prev();

            if (picForVote.length === 0) {
               $('div[ng-click="$ctrl.submit()"]').click();
               await new Promise(resolve => setTimeout(resolve, 4000));
               $('div[ng-click="$ctrl.close()"]').click();
               await new Promise(resolve => setTimeout(resolve, 4000));
               continue;

            } else {
               await picForVote.each(function (i, el) {
                  r = Math.random();
                  if (i >= 10 && r > 0.2) {
                     $(el).click();
                  }
               });
               await new Promise(resolve => setTimeout(resolve, 4000));
               $('div[ng-click="$ctrl.submit()"]').click();
               await new Promise(resolve => setTimeout(resolve, 4000));
               $('div[ng-click="$ctrl.close()"]').click();
               await new Promise(resolve => setTimeout(resolve, 4000));
            }
         }

         console.log("\n------------------------------------------------\nVoting Done\n------------------------------------------------\n");
         console.log("Trying for free boosts");
         if (boostBtns.length >= 1) {
            for (var btn of boostBtns) {
               $(btn).click();
               await new Promise(resolve => setTimeout(resolve, 4000));
               const picForVote = document.querySelector('div.c-modal-boost__photos > div:nth-child(1)');
               $(picForVote).click();
               await new Promise(resolve => setTimeout(resolve, 4000));
            }
         } else {
            console.log("No free boosts available");
         }


      })
      await browser.close();
      await console.log('\n------------------------------------------------\nFinished Session\n------------------------------------------------\n\n\n');
   })()
//});
```

**Comment by mshonak** [comment]
I success to run with random sleep time with powershell this code : 
( save this script to file  sleep.ps1 ) 

function Start-Sleep($seconds) {
    $doneDT = (Get-Date).AddSeconds($seconds)
    while($doneDT -gt (Get-Date)) {
        $secondsLeft = $doneDT.Subtract((Get-Date)).TotalSeconds
        $percent = ($seconds - $secondsLeft) / $seconds * 100
        Write-Progress -Activity "Sleeping" -Status "Sleeping..." -SecondsRemaining $secondsLeft -PercentComplete $percent
        [System.Threading.Thread]::Sleep(500)
    }
    Write-Progress -Activity "Sleeping" -Status "Sleeping..." -SecondsRemaining 0 -Completed
}
while (1) 
{
cd C:\GurushotsVoter
node main.js
    $SLEEPTIME = powershell -Command Get-Random -Minimum 1800 -Maximum 3600
    Write-output "Randomizing between voting sessions : sleeping for $SLEEPTIME"
   start-sleep -seconds $SLEEPTIME
}

**Comment by maatt** [comment]
strange, i'll test on windows later, works fine on mac and Ubuntu.

for `git` to work you need git installed `https://git-scm.com/download/win` otherwise yes just download and extract.
this might work:
`npm i node-cron`

**Comment by sbursik** [comment]
npm install cron will get your cron features working. Look at the top of the script. The modules called need to be installed. It doesn't mention this in the instructions. Using powershell run as administrator. Also needed to do: npm install puppeteer/npm install fs/npm install cron.  I installed git from https://gitforwindows.org/. Set my cron to 10 minutes and its working great

**Comment by mshonak** [comment]
I did : 
npm install puppeteer
npm install fs
npm install cron

Try to do : "npm start" got error "npm ERR! missing script: start" 

what is the benefit of using NPM , I run it with "node main.js " or use powershell to run sleep time randomly

**Comment by sbursik** [comment]
I don't know. I'm running it on Windows using Powershell and it works fine. I did have to open the shell as administrator to install the modules. Does your install path contain any spaces in the directories? That causes issues with my initial install when I tried to run it.

**Comment by freccia72** [comment]
Hi,
doesn't work. I did npm start remain in "starting node main.js"
After crash app.
What's wrong?

**Comment by maatt** [comment]
> Hi,
> doesn't work. I did npm start remain in "starting node main.js"
> After crash app.
> What's wrong?

thats working, the default cron is to run on the hour and every 30 minutes. 
so 1PM, 1:30PM, 2PM.. etc.. if you start the script at 5:46PM it wont run until 6PM.

**Comment by freccia72** [comment]
Maatt,
only a question. The script vote all the panel or until the exposure is full?
do It give real vote?
thanks

**Comment by Karljim** [comment]
Hello, how to deactivate free boost? Using the free boost is not always good especially in a challenge which last 14 days or more. It can destroy the tactic if wrong image being boosted. An idea, if the autovoter voting on the best voted photos it means it can degrade me. Is it possible to fix so that the voter is voting on the less voted images? And big thanks for the script!
